"""add_rapport_score_to_sessions

Revision ID: 24b90742e32c
Revises: f784534718ee
Create Date: 2026-01-19 20:53:22.617176
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24b90742e32c'
down_revision: Union[str, None] = 'f784534718ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('rapport_score', sa.Numeric(precision=5, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'rapport_score')
    # ### end Alembic commands ###
