"""initial

Revision ID: 629af0307cbf
Revises: 
Create Date: 2026-01-16 17:18:38.068396
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '629af0307cbf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('personas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('traits', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('default_mood', sa.String(length=50), nullable=False),
    sa.Column('voice_profile', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('system_prompt_template', sa.Text(), nullable=False),
    sa.Column('behavior_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scenarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('persona_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=False),
    sa.Column('scenario_rules', sa.Text(), nullable=False),
    sa.Column('success_criteria', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('book_rate', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('prior_context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("category IN ('outbound', 'inbound', 'manager')", name='check_scenario_category'),
    sa.CheckConstraint("difficulty IN ('easy', 'medium', 'hard', 'expert')", name='check_scenario_difficulty'),
    sa.CheckConstraint("type IN ('cold_call', 'discovery', 'demo', 'coaching', 'post_sales')", name='check_scenario_type'),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_scenarios_active', 'scenarios', ['is_active', 'is_locked'], unique=False)
    op.create_index('idx_scenarios_type', 'scenarios', ['type'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('rep', 'manager', 'admin')", name='check_user_role'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('idx_users_company', 'users', ['company_id'], unique=False)
    op.create_index('idx_users_role', 'users', ['role'], unique=False)
    op.create_table('training_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('manager_id', sa.UUID(), nullable=False),
    sa.Column('rep_id', sa.UUID(), nullable=False),
    sa.Column('scenario_id', sa.UUID(), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'in_progress', 'completed', 'overdue')", name='check_assignment_status'),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rep_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_assignments_manager', 'training_assignments', ['manager_id'], unique=False)
    op.create_index('idx_assignments_rep', 'training_assignments', ['rep_id', 'status'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('scenario_id', sa.UUID(), nullable=True),
    sa.Column('training_assignment_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('overall_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'in_progress', 'completed', 'abandoned')", name='check_session_status'),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['training_assignment_id'], ['training_assignments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sessions_created', 'sessions', ['created_at'], unique=False)
    op.create_index('idx_sessions_status', 'sessions', ['status'], unique=False)
    op.create_index('idx_sessions_user', 'sessions', ['user_id'], unique=False)
    op.create_table('conversation_states',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('turn_number', sa.Integer(), nullable=False),
    sa.Column('current_mood', sa.String(length=50), nullable=True),
    sa.Column('rapport_level', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('interest_level', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('objections_raised', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('rep_strengths_observed', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('rep_weaknesses_observed', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('conversation_summary', sa.Text(), nullable=True),
    sa.Column('dynamic_modifiers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_state_session_turn', 'conversation_states', ['session_id', 'turn_number'], unique=False)
    op.create_table('feedback',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('strengths', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('weaknesses', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('suggestions', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('highlighted_moments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_generated', sa.Boolean(), nullable=False),
    sa.Column('manager_comments', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_index('idx_feedback_session', 'feedback', ['session_id'], unique=False)
    op.create_table('session_analytics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('rep_talk_time_seconds', sa.Integer(), nullable=True),
    sa.Column('ai_talk_time_seconds', sa.Integer(), nullable=True),
    sa.Column('talk_listen_ratio', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('total_turns', sa.Integer(), nullable=True),
    sa.Column('rep_turns', sa.Integer(), nullable=True),
    sa.Column('ai_turns', sa.Integer(), nullable=True),
    sa.Column('avg_rep_response_time_ms', sa.Integer(), nullable=True),
    sa.Column('interruption_count', sa.Integer(), nullable=True),
    sa.Column('objection_handling_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('question_quality_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('professionalism_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('persuasiveness_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('goal_completion', sa.Boolean(), nullable=True),
    sa.Column('behavior_markers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sentiment_timeline', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_index('idx_analytics_session', 'session_analytics', ['session_id'], unique=False)
    op.create_table('transcripts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('turns', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('raw_audio_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_index('idx_transcripts_session', 'transcripts', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_transcripts_session', table_name='transcripts')
    op.drop_table('transcripts')
    op.drop_index('idx_analytics_session', table_name='session_analytics')
    op.drop_table('session_analytics')
    op.drop_index('idx_feedback_session', table_name='feedback')
    op.drop_table('feedback')
    op.drop_index('idx_state_session_turn', table_name='conversation_states')
    op.drop_table('conversation_states')
    op.drop_index('idx_sessions_user', table_name='sessions')
    op.drop_index('idx_sessions_status', table_name='sessions')
    op.drop_index('idx_sessions_created', table_name='sessions')
    op.drop_table('sessions')
    op.drop_index('idx_assignments_rep', table_name='training_assignments')
    op.drop_index('idx_assignments_manager', table_name='training_assignments')
    op.drop_table('training_assignments')
    op.drop_index('idx_users_role', table_name='users')
    op.drop_index('idx_users_company', table_name='users')
    op.drop_table('users')
    op.drop_index('idx_scenarios_type', table_name='scenarios')
    op.drop_index('idx_scenarios_active', table_name='scenarios')
    op.drop_table('scenarios')
    op.drop_table('personas')
    op.drop_table('companies')
    # ### end Alembic commands ###
