"""add_analytics_enhancements

Revision ID: f784534718ee
Revises: 629af0307cbf
Create Date: 2026-01-19 20:38:04.760714
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f784534718ee'
down_revision: Union[str, None] = '629af0307cbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('milestone_definitions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('criteria_type', sa.String(length=50), nullable=False),
    sa.Column('criteria_target', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_index('idx_milestone_def_active', 'milestone_definitions', ['is_active'], unique=False)
    op.create_table('user_milestones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('milestone_id', sa.UUID(), nullable=False),
    sa.Column('current_progress', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['milestone_id'], ['milestone_definitions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_milestone_completed', 'user_milestones', ['user_id', 'completed'], unique=False)
    op.create_index('idx_user_milestone_milestone', 'user_milestones', ['milestone_id'], unique=False)
    op.create_index('idx_user_milestone_user', 'user_milestones', ['user_id'], unique=False)
    op.create_table('user_skill_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('closing_skills', sa.Integer(), nullable=False),
    sa.Column('objection_handling', sa.Integer(), nullable=False),
    sa.Column('empathy_rapport', sa.Integer(), nullable=False),
    sa.Column('discovery_efficiency', sa.Integer(), nullable=False),
    sa.Column('value_proposition', sa.Integer(), nullable=False),
    sa.Column('last_calculated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('closing_skills >= 0 AND closing_skills <= 100', name='check_closing_skills_range'),
    sa.CheckConstraint('discovery_efficiency >= 0 AND discovery_efficiency <= 100', name='check_discovery_efficiency_range'),
    sa.CheckConstraint('empathy_rapport >= 0 AND empathy_rapport <= 100', name='check_empathy_rapport_range'),
    sa.CheckConstraint('objection_handling >= 0 AND objection_handling <= 100', name='check_objection_handling_range'),
    sa.CheckConstraint('value_proposition >= 0 AND value_proposition <= 100', name='check_value_proposition_range'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('idx_skill_scores_user', 'user_skill_scores', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_skill_scores_user', table_name='user_skill_scores')
    op.drop_table('user_skill_scores')
    op.drop_index('idx_user_milestone_user', table_name='user_milestones')
    op.drop_index('idx_user_milestone_milestone', table_name='user_milestones')
    op.drop_index('idx_user_milestone_completed', table_name='user_milestones')
    op.drop_table('user_milestones')
    op.drop_index('idx_milestone_def_active', table_name='milestone_definitions')
    op.drop_table('milestone_definitions')
    # ### end Alembic commands ###
